### PR TITLE
Allow passing extra params to tasks

### PR DESCRIPTION
**Pull request by sebastien-p**
So that we can easily pass stuff like a paths object, plugins loaded using jackfranklin/gulp-load-plugins, ...

If the pull request ends up merged, I'd be happy to document the changes :smile:.

### CODE REVIEW

**Comment by rummik** [comment]
So, there are a few issues with the changes here:
- Unnecessary indentation changes (makes diffs difficult to read, breaks clean merging)
- Doc headers were removed, rather than updated
- Single-line if statements (project preference)

A quick look at your profile shows this is your first code-related PR?  It's a good idea to note that, in the future, when making PRs you should use the same style as the surrounding code, primarily since it avoids the first issue I list, but also because many projects have a specific writing style they prefer.  :)

**Comment by sebastien-p** [comment]
You are totally right, I'll sync and apply the changes again making sure your code style is preserved. Thanks!

**Comment by rummik** [comment]
Looking forward to it!

**Comment by sebastien-p** [comment]
So I finally found the time to do it, hopefully this time I did it correctly: #5.

**Pull request closed without merging**
